language: node_js
node_js:
 - stable
deploy:
  provider: npm
  email: mikededys@gmail.com
  api_key:
    secure: GwUEnHUMKBfwkj9MuStgghxgokAtjVU3gPLqdzq+E29mH7Wx7JhQtX0v8BNU5uyaAudp4z3VacrFVAantspsNTpNoWFwJAbKTiRI2F8k79RocMfsUUd2s0tXjEaZj4b0vzgppC+bRe4lvf/20j+iEEGh71Be36eRgvuzd3Ez3tVbAUz0o5DdXlgzAqhGxMJUewbnZcWt1n8mH2e6aE2QX4p9y74QxC8rma4BjLDyCZ8fzjiyPFNs9RDRDrf5BAFz0bZ/56qve8iSWODTA294MwIYfD9IR2I4XBbXnY+ds0YdAw9EA8g+SY2YUohvL3TlmZoWFLgwjvTkE2H3/BW6ni1qi686bJxIwDNs0nvjQ/DgU9QLyu6jUWmAuReTzAja1T70r7mhhK9gh1kal8VEXVbsaeQ+lZ7lJIWfs2OUKHeIZ8ZQPvAMMjVYJ5YvV4aLprYdgRDBkEfoznJ3rIEFNl1PuQgOljWPYBHiW0jZ3ArqO9kjuURbUMAtkxlEpv9iZbXFce489cfeXgUNsHerwIJ8KS7gXRVx3aGA85xjnlekgFsozJ1gupGRa+OcJU75S2nXYLNY9GZ8PGgWtg4gh1wWNDixoU5yTPzXDsEOJjMVSiOTj9B4RgpPeDyM1CAEzLpGDes6clYiiYE0BgV1BIm1AgjmCYYS3I/yz3cKTAI=
  on:
    tags: true
    branch: master
