version: 2.1

defaults: &defaults
  working_directory: ~/repo

orbs:
  node: circleci/node@2.0.3
jobs:
  build-and-test:
    <<: *defaults
    executor:
      name: node/default
    steps:
      - node/test:
          version: 13.11.0
  deploy:
    <<: *defaults
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish Package
          command: npm publish
workflows:
  build-and-test:
    jobs:
      - build-and-test
  deploy:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - build-and-test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
