version: 2.1

defaults: &defaults
  working_directory: ~/repo

orbs:
  node: circleci/node@2.0.3

jobs:
  test:
    <<: *defaults
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/repo
          pkg-manager: yarn
          cache-key: yarn.lock
      - run:
          name: "Copy fonts.conf"
          command: cp ./circleci/fonts.conf ~/.fonts.conf
      - run: yarn test
  deploy:
    <<: *defaults
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish Package
          command: npm publish

workflows:
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
